[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ygz_citibike_dab_project"
version = "0.0.1"
authors = [{ name = "106018876@student.swin.edu.au" }]
description = "This contains the code in the ./src directory of the project"
requires-python = ">=3.10,<3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
    "databricks-dlt",
    "databricks-connect>=15.4,<15.5",
    "ipykernel",
    "pyspark>=4.0.0",
]

[project.scripts]
main = "ygz_citibike_dab_project.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.ruff]
line-length = 120
